# Exported from Render on 2024-07-27T16:25:02Z
services:
- type: web
  name: next-docker-starter-kit
  runtime: node
  repo: https://github.com/alamenai/next-docker-starter-kit
  plan: starter
  envVars:
  - key: PORT
    sync: false
  region: frankfurt
  buildCommand: npm install && npm run build
  startCommand: npm start
version: "1"
